server:
  port: 8180

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址

  application:
    name: service-statistics
  profiles:
    active: dev

  datasource:
    username: root
    password: yang19960506
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_statistics?serverTimezone=GMT%2B8

  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/guli/service/edu/mapper/xml/*.xml


feign:
  sentinel:
    enabled: true

ribbon:
  ConnectTimeout: 60000 #连接建立的超时时长，默认1秒
  ReadTimeout: 60000 #处理请求的超时时间，默认为1秒