server:
  port: 8170

spring:
  application:
    name: service-trade

  datasource:
    url: jdbc:mysql://localhost:3306/guli_trade?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yang19960506
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        port: 8081 #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080 # 指定控制台服务的地址
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/atguigu/guli/service/edu/mapper/xml/*.xml

ribbon:
  ConnectTimeout: 60000 #连接建立的超时时长，默认1秒
  ReadTimeout: 60000 #处理请求的超时时间，默认为1秒

feign:
  sentinel:
    enabled: true

weixin:
  pay:
    #关联的公众号appid
    appId: wxf913bfa3a2c7eeeb
    #商户号
    partner: 1543338551
    #商户key
    partnerKey: atguigu3b0kn9g5v426MKfHQH7X8rKwb
    #回调地址
    notifyUrl: http://imqiaoyu.free.idcfengye.com/api/trade/weixin-pay/callback/notify